language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_install:
  - npm install -g coveralls
script:
  - npm install
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls
